### ISSUE TITLE
copy of the table with issue

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/simcard#43]
I would like to copy my db and I have an error on simcard plugin

sql error (1054) Unknown column 'notepad' in 'field list'

**Comment by btry** [comment]
Hi,

Can you tell the versions of glpi and pkugins for both source and destination ?

**Comment by satyan01** [comment]
0.90.1 version is used

**Comment by btry** [comment]
How do you backup and restore your database : 
- fron the interface of GLPI, 
- or with mysqldump ?

**Comment by satyan01** [comment]
with heidisql

**Comment by btry** [comment]
If the same version of GLPI and the plugin are in both sides, I wonder how you get a different database model.

Can you show the buggy query ? I need to check which table is missing its column.

**Comment by satyan01** [comment]
I copy my database and I upgrade my glpi at each time. Actually we are using two servers. one on 0.85.2 one staging on 0.90.1 will be in production as soon as possible

**Comment by btry** [comment]
Then the error occurs when you click on the  "upgrade" button of the plugin, doesn't it ?

**Comment by satyan01** [comment]
no just when I try to copy glpi database in heidisql

**Comment by btry** [comment]
Hi

The column notepad has been removed in september 2015, because starting from GLPI 0.85, it became useless. I *guess* you were using a 1.4 release candidate before this date.

You may manually create the column "notepad" in your staging GLPI instance to workaroud the issue. If you have at least one simcard having something in this column, then you have to migrate this column with a query. Have a look in inc/simcard.class.php, method upgrade() : there is a loop to execute the migration and it should be possible to do the same with a single query.

**Comment by satyan01** [comment]
solved. Thx
